### ISSUE TITLE
Why does calibre-web.log show blank lines?

### ISSUE THREAD

**Issue by holta** [iiab/calibre-web#100]
Is this an upstream issue in Calibre-Web?

Regardless: Can we fix it and how?

MOTIVATION: IIAB's version of Calibre-Web needs extremely Clean + Meaningful logging — as literally every aspect of growing communities depends on this foundation.

Example:

`/var/log/calibre-web.log` blank lines on [962](https://sprunge.us/16LYXQ?en#n-962) and [1001](https://sprunge.us/16LYXQ?en#n-1001)

Related:

- #68
- #70
- https://github.com/iiab/calibre-web/pull/96#issuecomment-1892922376

**Comment by holta** [comment]
@deldesir is still an issue?

(Or if blank lines are much more rare in `/var/log/calibre-web.log` now, what is the reason?)

**Comment by deldesir** [comment]
Not anymore. Let's close this issue for now.
