### ISSUE TITLE
Videos sometimes fail to "Download to IIAB" w/ message: 405 METHOD NOT ALLOWED

### ISSUE THREAD

**Issue by holta** [iiab/calibre-web#106]
Example video that failed for @avni: (in a Multipass 1.13.0 VM on Mac)

"India-Pakistan partition explained"
https://www.youtube.com/watch?v=OnTYLyNUPMc

![image](https://github.com/iiab/calibre-web/assets/2458907/bab3f874-2872-4bae-89e7-b29cef4affbf)

iiab-diagnostics:

- https://sprunge.us/Ujlsn8?en
- https://sprunge.us/Ujlsn8?en#n-805

@deldesir: are these 2 issues below related or no?

- #85 
- #101

Tangentially related, also from @avni:

- #77

**Comment by avni** [comment]
Adding git log per @holta's request: 

ubuntu@box:/usr/local/calibre-web-py3$ cd /usr/local/calibre-web-py3; sudo git log --graph --oneline --decorate | head -50
*   57587157 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #103 from deldesir/deldesir-patch-6
|\  
| * 15a344a6 Fix shelf regression
|/  
*   a2911a2a Merge branch 'janeczku:master' into master
|\  
| * b9c32953 Fix for #2980 (invalid seriesindex causes no longer a crash)
* |   a860a789 Merge pull request #102 from deldesir/deldesir-upload
|\ \  
| * | 5b85eb3d Return True to confirm success
| * | 135ecd0d Remove links enumeration
| * | 989f1f79 Revert to upload task
|/ /  
* |   23dde793 Merge pull request #96 from deldesir/deldesir-database
|\ \  
| * | 1d81c1f7 Show uploaded files link
| * | 91839f23 Remove whitespace
| * | 782d1594 Remove whitespace
| * |   723c0bf3 Merge branch 'iiab:master' into deldesir-database
| |\ \  
| |/ /  
|/| |   
* | |   659c00c5 Merge pull request #95 from deldesir/deldesir-error-handling
|\ \ \  
| | * | a348429a Enhance database operations for better error handling
| |/ /  
| * | b3f39b35 Remove flash import
| * |   47f07bbe Merge branch 'iiab:master' into deldesir-error-handling
| |\ \  
| |/ /  
|/| |   
* | |   b80aaa77 Merge pull request #94 from deldesir/deldesir-patch-5
|\ \ \  
| * | | b6d90121 Get lb-wrapper command directly : cps/tasks/download.py
|/ / /  
| * / daef51f0 Improve error handling
|/ /  
* | a84f4a06 Merge branch 'janeczku:master' into master
|\| 
| * 898e76fc re enable gevent
| * af71a1a2 Fix for #2973 (No unix sockets on windows available)
* |   d68cbeed Merge pull request #90 from deldesir/deldesir-messages
|\ \  
| * | 8a095636 Change fetching to downloading in cps/editbooks.py
| * | e3d75ffc Update initial status message in editbooks.py
| * | 95546864 Rephrase status messages
| * |   4a2bff34 Merge branch 'iiab:master' into deldesir-messages
| |\ \  
| |/ /  
|/| |

**Comment by holta** [comment]
FWIW https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405 says...

> 405 Method Not Allowed
> The HyperText Transfer Protocol (HTTP) 405 Method Not Allowed response status code indicates that the server knows the request method, but the target resource doesn't support this method.
>
> The server must generate an Allow header field in a 405 status code response. The field must contain a list of methods that the target resource currently supports...

**Comment by holta** [comment]
Thanks to @deldesir who explained:

> Avni's video downloaded at https://lrn2.org/live/book/311

> I had to restart LRN2. The issue is once Calibre-Web is blocked by an incomplete download, it's blocked until restarted. This must be fixed to avoid frustrations.

**Comment by avni** [comment]
Interesting, so if I restarted my IIAB instance, the video would complete downloading? Is that how you were able to get it to complete downloading?

**Comment by deldesir** [comment]
@holta, see line 891:
 `891 [2024-01-20 14:24:30,697] ERROR {cps.tasks.download:110} Failed to send the list of requested files to http://192.168.64.16/books/media?data=root&sort_param=stored `

The URL should be `http://192.168.64.16/books/media` without any query parameters. @avni do you remember from which you were calling/using the download button?

**Comment by holta** [comment]
> The URL should be `http://192.168.64.16/books/media` without any query parameters.

https://sprunge.us/Ujlsn8?en#n-891

(Root cause possibly... not too complex?)

**Comment by deldesir** [comment]
I am curious. Why the download was attempted using the **books/media** route instead of the **books/meta** one? I am still investigating...

**Comment by deldesir** [comment]
> Interesting, so if I restarted my IIAB instance, the video would complete downloading? Is that how you were able to get it to complete downloading?

Yes. There were already some one hanging download in the queue and a couple of others waiting to be started once the first one (which stuck) to finish.

**Comment by avni** [comment]
> Yes. There was already one hanging download in the queue and a couple of others waiting to start once the first one (which stuck) finished. This issue was already reported in #58.

Very odd as this was the first video I tried. 

> @avni do you remember from which page you were calling/using the download button?

http://192.168.64.16/books/?data=root&sort_param=stored 

Interestingly, when I just tried from: http://192.168.64.16/books/tasks, it did work. 
When I start from books/ it gives the same 405 error. 

http://sprunge.us/hphHmX

<img width="1100" alt="Screenshot 2024-01-20 at 6 21 36 PM" src="https://github.com/iiab/calibre-web/assets/47825/05ce383d-5892-4145-ab50-0432c7e467bc">

**Comment by holta** [comment]
@avni thanks so much for helping others to solve this 🙏 

Direct link for @deldesir & others investigating:

https://sprunge.us/hphHmX?en#n-909

**Comment by avni** [comment]
Confirmed! I tried from both http://192.168.64.17/books/ and http://192.168.64.16/books/tasks and it now works. Thank you!
