### ISSUE TITLE
Automate bookshelves creation and population

### ISSUE THREAD

**Issue by deldesir** [iiab/calibre-web#11]
**Describe the Problem**

Currently, in Calibre-Web, the creation and population of bookshelves are manual processes, dependent on user decisions after each upload/download. This manual approach can become time-consuming and less user-friendly, especially when multiple downloads occur.

The proposal is to automate the process of creating and populating bookshelves upon the occurrence of multiple downloads. This automation should streamline the organization of downloaded content and enhance user experience by reducing manual efforts. 

**Proposed Changes**

1. **Automated Bookshelf Creation**: Implement a feature to automatically create bookshelves based on specified criteria (e.g., playlist title, custom name) for downloaded content.
2. **Populating Bookshelves**: Upon download completion, the system will automatically organize and populate the appropriate bookshelves based on predefined rules or user settings.
3. **Customizable Automation**: Provide users with the flexibility to customize the automation settings, allowing for personalized organization rules and preferences. This should be defaulted to available collection title. The current frontend code for the download modal dialog is misleading. It must be removed or optimized for custom naming/renaming of bookshelves.
4. **User Notification**: Notify users about the automated creation and population of bookshelves, ensuring transparency and awareness of the organization process.

**Expected Outcomes**

By automating the creation and population of bookshelves upon multiple downloads, the goal is to significantly reduce manual efforts for users, improving the organization and accessibility of downloaded content within Calibre-Web.

**Additional Context**

The aim of this proposed change is to enhance the user experience by automating the organization process without compromising user control. This enhancement seeks to minimize the burden on users in organizing downloaded content while allowing for customization and user-defined parameters for automation.

**Comment by holta** [comment]
> Provide users with the flexibility to customize the automation settings, allowing for personalized organization rules and preferences.

For now, please https://en.wikipedia.org/wiki/KISS_principle — with the most minimal/viable front-end please!

> This should be defaulted to available collection title. The current frontend code for the download modal dialog is misleading. It must be removed or optimized for custom naming/renaming of bookshelves.

👍

**Comment by holta** [comment]
Design Question:

Can we guarantee that all new bookshelf auto-creation never fails, using simple (slug-like) naming scheme like...

- MichaelJackson
- MichaelJackson (2)
- MichaelJackson (3)

**Comment by deldesir** [comment]
Good idea!

**Comment by deldesir** [comment]
I closed this as completed. We'll revisit it when frontend works start to incorporate a field to override name resolution from playlists/channels titles.

**Comment by holta** [comment]
> I closed this as completed. We'll revisit it when frontend works start to incorporate a field to override name resolution from playlists/channels titles.

Related:

- https://github.com/iiab/calibre-web/issues/107#issuecomment-2182655102
