### ISSUE TITLE
"Task progress should within [0, 1] range" appeared in Tasks, on downloading 36-video playlist

### ISSUE THREAD

**Issue by holta** [iiab/calibre-web#129]
An attempt to download a 36 video playlist https://www.youtube.com/playlist?list=PLU6sEQK7ize-4xjVnhQhgDQVcRaHO_y8p went successfully although initially gives failed:Task progress should be within [0,1 ] range.All videos downloaded successfully though.I have ran diagnostics  again ,this is the very last part of my tests.
 IIAB-DIAGNOSTICS http://sprunge.us/Colc0b?en
![Screenshot from 2024-02-09 22-56-44](https://github.com/iiab/calibre-web/assets/52469992/6225af72-b016-4a6e-81ad-87e4c5665bde)

_Originally posted by @EMG70 in https://github.com/iiab/calibre-web/issues/125#issuecomment-1950256765_

**Comment by deldesir** [comment]
Looking into it.

One video from the playlist failed for me: https://m.youtube.com/watch?v=VvUZcy-KPgo

**Comment by holta** [comment]
> One video from the playlist failed for me: https://m.youtube.com/watch?v=VvUZcy-KPgo

Likely true for everyone... error message I get is:

"This video isn't available anymore"

**Comment by deldesir** [comment]
The failed video caused the error. I'll address this in a PR so exceptions like these are caught and handled gracefully.

**Comment by holta** [comment]
1) Great it's understood!

2) English phrase "Task progress should within" should probably be cleaned up too?

   > "Task progress should be within [0, 1] range"

   QUESTION: Is this about percentages — e.g. {0, 1, 2, 3, 4... 97, 98, 99, 100%} ?

**Comment by deldesir** [comment]
If a playlist contains 10 videos. The length of the list of all videos will be 10. The progress is calculated as:
 _index of video / length of list of all videos _

The issue is caused by an increase of the number of requested videos while the length stays the same. 11/10 = 1.1

**Comment by holta** [comment]
@deldesir can you make PR #130's title a bit more explanatory for all?

Making more vividly clear what in fact changed here?

- PR #130

**Comment by deldesir** [comment]
> @deldesir can you make PR #130's title a bit more explanatory for all?
> 
> Making more vividly clear what in fact changed here?
> 
> - PR #130

Title for #130 changed.
