### ISSUE TITLE
1st row no longer visible when more than 20 tasks are processed

### ISSUE THREAD

**Issue by deldesir** [iiab/calibre-web#132]
When the 1st row (of "Tasks" view) is no longer visible in browser — as if that line has scrolled off the top — is the data still available to be viewed if you open the same page with a much larger browser on a much larger screen?

_Originally posted by @holta in https://github.com/iiab/calibre-web/issues/130#issuecomment-1952669453_

**Comment by holta** [comment]
Good enough at this time:

- PR #133

Thanks @EMG70 for having tested.
