### ISSUE TITLE
https://www.youtube.com/shorts/oVrgbLm_J30 fails to download at CLI if `lb dl` command contains `--search` [whereas "Download to IIAB" button works!]

### ISSUE THREAD

**Issue by holta** [iiab/calibre-web#136]
1st step succeeds:

```
lb-wrapper tubeadd https://www.youtube.com/shorts/oVrgbLm_J30
```

Equivalent to...

```
lb tubeadd /library/calibre-web/xklb-metadata.db https://www.youtube.com/shorts/oVrgbLm_J30 --force -vv
```

2nd step fails, with error message `No media found` and exit code / error code 2:

```
lb-wrapper dl https://www.youtube.com/shorts/oVrgbLm_J30
```

Equivalent to...

```
lb dl /library/calibre-web/xklb-metadata.db --prefix /library/downloads/calibre-web --video --search https://www.youtube.com/shorts/oVrgbLm_J30 --write-thumbnail -vv
```

Whereas removing `--search` appears to work every time:

```
lb dl /library/calibre-web/xklb-metadata.db --prefix /library/downloads/calibre-web --video https://www.youtube.com/shorts/oVrgbLm_J30 --write-thumbnail -vv
```

_Finally, @deldesir suggests that clicking "Download to IIAB" worked with https://www.youtube.com/shorts/oVrgbLm_J30 very mysteriously — even despite (he says) `--search` being baked into the lb-wrapper command on the particular machine in question?_

Somewhat related:

- #114
- #135

**Comment by holta** [comment]
> Finally, @deldesir suggests that clicking "Download to IIAB" worked with https://www.youtube.com/shorts/oVrgbLm_J30 very mysteriously — even despite (he says) --search being baked into the lb-wrapper command on the particular machine in question?

@deldesir please provide full details (including pastebin URL after running `sudo iiab-diagnostics`) to help everyone try to understand why your screenshots below are... _very different from repeated CLI failures..._ Thank you!

![image](https://github.com/iiab/calibre-web/assets/2458907/3854fe6e-d80b-43d7-a2ba-5d289fc37890)

![image](https://github.com/iiab/calibre-web/assets/2458907/eb353602-c731-4a2e-96cf-f11be54e5718)

**Comment by deldesir** [comment]
Why downloading through Calibre-Web succeeded and using the CLI failed? When we use the "Download to IIAB" button to download , here is what happens:
  1- `lb tubeadd` is run in the background against https://www.youtube.com/shorts/oVrgbLm_J30
  2- The standard URL is resolved automatically (https://www.youtube.com/watch?v=oVrgbLm_J30) and recorded in the database
  3- The `cps/tasks/download.py` reads the database and search for pending downloads, the standard URL (https://www.youtube.com/watch?v=oVrgbLm_J30) is found.
  4- `lb dl` is run in the background against **https://www.youtube.com/watch?v=oVrgbLm_J30**, not https://www.youtube.com/shorts/oVrgbLm_J30
  
The failure of CLI resides in xklb looking for the media file using https://www.youtube.com/shorts/oVrgbLm_J30 instead of the standard URL https://www.youtube.com/watch?v=oVrgbLm_J30 (which was not resolved)

**Comment by holta** [comment]
Thanks @deldesir for the detailed above explanation 🙏

Do you or @chapmanjacobd perceive any risks here going forward?

(Or should we close this ticket as concerning-but-harmless!)

**Comment by holta** [comment]
@deldesir I've marked this as "wontfix" so we drive focus on mainline use cases:

- Downloading https://www.youtube.com/shorts/oVrgbLm_J30 using "Download to IIAB" button certainly works.
- Whereas `lb-wrapper tubeadd https://www.youtube.com/shorts/oVrgbLm_J30` then `lb-wrapper dl https://www.youtube.com/shorts/oVrgbLm_J30` continues to fail:

```
/usr/local/bin/lb
/usr/local/bin/yt-dlp
2024-06-19 15:08:33 - [Info] Using yt-dlp 2024.05.27
2024-06-19 15:08:33 - [Info] Running xklb command: lb dl '/library/calibre-web/xklb-metadata.db' --video --search 'https://www.youtube.com/shorts/oVrgbLm_J30' --format best --format-sort 'tbr~1000' --write-thumbnail --subs -o '/library/downloads/calibre-web/%(extractor_key,extractor)s/%(uploader,uploader_id)s/%(title).170B_%(view_count)3.2D_[%(id).64B].%(ext)s' -vv
2024-06-19 15:08:33 - [Debug] library v2.8.065
2024-06-19 15:08:33 - [Debug] ['/usr/local/bin/lb', 'dl', '/library/calibre-web/xklb-metadata.db', '--video', '--search', 'https://www.youtube.com/shorts/oVrgbLm_J30', '--format', 'best', '--format-sort', 'tbr~1000', '--write-thumbnail', '--subs', '-o', '/library/downloads/calibre-web/%(extractor_key,extractor)s/%(uploader,uploader_id)s/%(title).170B_%(view_count)3.2D_[%(id).64B].%(ext)s', '-vv']
2024-06-19 15:08:34 - [Debug] {'include': ['https://www.youtube.com/shorts/oVrgbLm_J30'], 'subs': True, 'profile': 'video', 'paths': []}
2024-06-19 15:08:34 - [Debug] No media found
2024-06-19 15:08:34 - [Error] Error 2 occurred while running lb-wrapper's xklb commands.
```

(Ok to close this ticket now?)

**Comment by deldesir** [comment]
This is expected. Same issue will happen with any playlist URL. This issue can be closed unless we add a "resolver" to lb-wrapper.
