### ISSUE TITLE
Subsequent playlists redownloads fail

### ISSUE THREAD

**Issue by deldesir** [iiab/calibre-web#150]
IIAB-DIAGNOSTICS - http://sprunge.us/oECy1e?en
This playlist https://www.youtube.com/playlist?list=PLGjplNEQ1it_oTvuLRNqXfz_v_0pq6unW of 14 videos was downloaded successfully and videos in order of ranking.. see screenshot.

Subsequent download attempts for these below have all failed in tasks but an empty  bookshelf name is created.
https://www.youtube.com/playlist?list=PLGjplNEQ1it_oTvuLRNqXfz_v_0pq6unW  14 videos
https://www.youtube.com/playlist?list=PLfEr2kn3s-bo4LwlbyZugHPavhcdW8YMC               97 videos 
![Screenshot from 2024-03-27 14-51-32](https://github.com/iiab/calibre-web/assets/52469992/0fe734ad-7561-49af-9c46-2875e3049885)
![Screenshot from 2024-03-27 14-52-05](https://github.com/iiab/calibre-web/assets/52469992/0700f7e2-ede6-491b-8ccd-fcdea34f1844)
![Screenshot from 2024-03-27 14-55-11](https://github.com/iiab/calibre-web/assets/52469992/cf60582d-3235-44b6-847b-e9cbababadee)
![Screenshot from 2024-03-27 15-03-21](https://github.com/iiab/calibre-web/assets/52469992/510be9f9-ab42-424a-8e93-f14519a94290)

_Originally posted by @EMG70 in https://github.com/iiab/calibre-web/issues/146#issuecomment-2023012983_

**Comment by deldesir** [comment]
@EMG70, please let me know if your tests went well after applying fix #151 to your issue so I can close this ticket.

**Comment by deldesir** [comment]
@EMG70, I am still looking for the causes of the failures you experienced. Want to give it another try?

**Comment by EMG70** [comment]
I will try again in next 3hrs and update you.

**Comment by EMG70** [comment]
IIAB-DIAGNOSTICS - http://sprunge.us/Kv2wBX?en
https://www.youtube.com/playlist?list=PL_c9BZzLwBRLVh9OdCBYFEql6esA6aRsi - 102 short videos in playlist ✅
https://www.youtube.com/playlist?list=PLr6-GrHUlVf96NLj3PQq-tmEB6woZjwEl - 53 short videos in playlist ✅
97/102 Videos were downloaded OK.A few videos failed https://www.youtube.com/watch?v=4e3dIeP93E8 and https://www.youtube.com/watch?v=D2KvDBSZA0w although they do play well on Youtube.I am not sure why,see screenshot below:
![Screenshot from 2024-04-09 14-55-18](https://github.com/iiab/calibre-web/assets/52469992/df5c6211-c687-4a2e-b054-9e9121a86727)

**Comment by deldesir** [comment]
**UPDATE:**

Subsequent redownloads of same playlists fail.
- missing videos: a 102-videos playlists run downloaded only 9 videos in the second redownload, 0 in the third one. 

Subsequent downloads of different playlists work.

**Comment by holta** [comment]
@deldesir @EMG70

1) We need to monitor in early June confirming that PR #151 fixed this sufficiently.

2) If so, we need to update &/or clarify the explanation posted here for everyone:

   *[TODO] Supporting redownloading videos with the same ID*
   https://github.com/iiab/calibre-web/wiki#todo-supporting-redownloading-videos-with-the-same-id

3) Somewhat related: - #153

**Comment by holta** [comment]
> @deldesir @EMG70

>
> 1. We need to monitor in early June confirming that PR https://github.com/iiab/calibre-web/pull/151 fixed this sufficiently.

3 weeks have passed: can we get to a conclusion here now?

**Comment by EMG70** [comment]
I will test again and update you today.

**Comment by holta** [comment]
> I will test again and update you today.

@deldesir let us know if we should close this issue, Thanks!

**Comment by deldesir** [comment]
Since subsequent playlist redownloading is not an issue anymore, this ticket should be closed.

**Comment by holta** [comment]
> Since subsequent playlist redownloading is not an issue anymore, this ticket should be closed.

@EMG70 please confirm with your own URL & results when redownloading it! 🙏

**Comment by EMG70** [comment]
SUDO IIAB-DIAGNOSTICS - https://dpaste.com/9RWTE5BFG
I have used same playlists that had some failing videos last time.I can confirm all downloaded  100 % OK .I did not see any reason to re-download same playlist today as all  were successful.
https://www.youtube.com/playlist?list=PL_c9BZzLwBRLVh9OdCBYFEql6esA6aRsi 102 videos ✅
https://www.youtube.com/playlist?list=PLr6-GrHUlVf96NLj3PQq-tmEB6woZjwEl  55 videos  ✅

**Comment by holta** [comment]
Good enough.

Thanks @EMG70 and please keep an eye on any video redownloading gotchas that might re-surface in future!
