### ISSUE TITLE
Videos failed and triggers "UNIQUE constraint failed: media.path" error on first retry/redownload

### ISSUE THREAD

**Issue by deldesir** [iiab/calibre-web#153]
When I force the redownload of failed video (due to unavailable fragments), I got the UNIQUE constraint failed: media.path error:
   1- no error was reported by xklb for the failed video. It's like the video succeeded and even got a download/local "path"
   2- since the video really failed, calibre-web did not have it, so no timestamp was added to the path

![image](https://github.com/iiab/calibre-web/assets/16546989/b5832340-ba80-4a51-a27d-b92ff87eeed3)

_Originally reported by @EMG70 in https://github.com/iiab/calibre-web/pull/151#issuecomment-2045278118_

**Comment by deldesir** [comment]
This video downloads fine now (https://www.youtube.com/watch?v=EQCUdCG-eAA)

![image](https://github.com/iiab/calibre-web/assets/16546989/460e5031-8330-4667-8915-147b47d23a95)

**Comment by holta** [comment]
> This video downloads fine now (https://www.youtube.com/watch?v=EQCUdCG-eAA)

@EMG70 can we close this now?

**Comment by EMG70** [comment]
> > This video downloads fine now (https://www.youtube.com/watch?v=EQCUdCG-eAA)
> 
> @EMG70 can we close this now?

Yes Please go ahead and close it.
