### ISSUE TITLE
Channel downloads fail due to residual shorts duplicates

### ISSUE THREAD

**Issue by deldesir** [iiab/calibre-web#154]
When downloading channels, Shorts are duplicated in the database. For example, if a channel contains https://www.youtube.com/shorts/fXUqA0TqONQ, 2 entries will be created:

1- https://www.youtube.com/shorts/fXUqA0TqONQ with no time_uploaded, live_status, size and duration
2- https://www.youtube.com/watch?v=fXUqA0TqONQ fully updated

**Comment by holta** [comment]
Tangentially related:

- PR #151
