### ISSUE TITLE
Single videos failed to download on LRN2 despite reinstall of Calibre-Web

### ISSUE THREAD

**Issue by deldesir** [iiab/calibre-web#166]
Videos will fail due to unavailable fragments. Seems the same timeout issue mentioned in #165 (or something more serious) is happening there.

**Comment by holta** [comment]
Disturbing!

We need to figure out what's happening as almost all software (ansible-core, xklb, yt-dlp, etc) was reinstalled on LRN2.ORG last night — right after it was upgraded from Ubuntu 22.04 to 24.04.

**Comment by holta** [comment]
CLARIF / RECAP: @deldesir tried deleting `/library/calibre-web/xklb-metadata.db` just in case XKLB's schema recently changed — but this did not help:

Clicking "Download to IIAB" trying to download (https://www.youtube.com/watch?v=_i_Rnq6VVOo) again failed.

**Comment by deldesir** [comment]
Fixed by #170
