### ISSUE TITLE
Clarify actions on Book Details overlay

### ISSUE THREAD

**Issue by avni** [iiab/calibre-web#176]
**Describe the bug/problem** 

When clicking on a specific book, a "Book Details" overlay shows up, that has two checkboxes, "Read", and "Archived". It's not clear what the implications of clicking on these checkboxes is. I can guess that clicking on "Archived" will mean it no longer shows up on the main Books page but it's not explicit. I do not know what clicking on "Read" does. I also recommend changing the lables to present tense/an action verb instead of past tense. 

**Screenshots**

![Image](https://github.com/iiab/calibre-web/assets/47825/16012d5b-bbc2-4da8-bcf9-2a86ca1604d9)

**Comment by holta** [comment]
FWIW the actual/original/upstream Calibre-Web imposes these.

When you log out (instead of logging in with Admin/changeme) do these 2 checkboxes presumably go away?

**Comment by avni** [comment]
>FWIW the actual/original/upstream Calibre-Web imposes these.

Good to know. Is it possible to override or request the changes be made upstream? 

>When you log out (instead of logging in with Admin/changeme), are these 2 checkboxes presumably no longer clickable?
The checkboxes and associated labels do not show up when you are logged out.


![Image](https://github.com/iiab/calibre-web/assets/47825/2e5f8ece-b6ae-434f-85a7-23e6ad98469c)

**Comment by holta** [comment]
> Is it possible to override or request the changes be made upstream?

Possible.  However there are so many other high-urgency needs in the pipeline 😶‍🌫️ that UX/UI improvements here might be a few years away?

**Comment by avni** [comment]
Closing in favor of: https://github.com/janeczku/calibre-web/issues/3076
