### ISSUE TITLE
Shouldn't "Metadata Fetch" show Progress 100% ?

### ISSUE THREAD

**Issue by holta** [iiab/calibre-web#205]
Downloading https://www.youtube.com/watch?v=ZeSJfoo2tR0 was successful, on a fresh install of IIAB Calibre-Web on Ubuntu 24.10 (latest pre-release).

Shouldn't the initial "Metadata Fetch" stage below also show Progress 100%, once that stage completes?

![image](https://github.com/iiab/calibre-web/assets/2458907/1853f981-004c-4a2a-a8d5-8fdccfd3a81e)

iiab-diagnostics: https://dpaste.com/A9V27XJ9Z

**Comment by deldesir** [comment]
It's obviously a race condition issue. The polling couldn't be done in just 3 seconds.

**Comment by holta** [comment]
I might be wrong: but just FYI my observation from recent screenshots is that Metadata Fetch seems to result in Progress "0%" almost every time?

(Or maybe every single time!)

**Comment by holta** [comment]
CLARIF: This is NOT a showstopper bug obviously!

Still, it creates unnecessary UX confusion — so we should try to understand it better and fix this in coming months. :pray:
