### ISSUE TITLE
Dialog modal do not dismiss when "Enter" key is pressed

### ISSUE THREAD

**Issue by deldesir** [iiab/calibre-web#22]
**Describe the bug/problem**

When submitting a download task, the dialog modal does not disappear on Enter key press even though this does not prevent the process from being run.

**To Reproduce**

Press Enter key submitting a URL in the "Download" form.

**Expected behavior**

The dialog modal should just dismiss.

**Environment (please complete the following information):**
 - OS: Ubuntu 23.10
 - Python version: 3.11.6
 - Calibre-Web version: 0.6.21 - Romesa (customized per #7 )
 - Docker container: No
 - Special Hardware: No
 - Browser: Firefox Nightly 121.0a1 (2023-11-3) (64-bit) 

**Additional Context**

This is about the Dialog modal displayed when clicking on the "Download" button.

**Comment by holta** [comment]
> The dialog modal should just dismiss.

Oftentimes "Enter" is expected to perform the default behavior...

...which would be "Start" in this case, right?

**Comment by holta** [comment]
A counterargument:

Large downloads should never be started accidentally... ?

(Completely ignoring most/all "Enter" key presses... might be another option to consider?)

**Comment by holta** [comment]
Discussed with @deldesir:

- Our conclusion is that evolving **UX/browser norms should be strongly respected** (e.g. `Enter` key should move you forward if you're working in a textfield and then click `Enter`, if that's indeed the normal/modern web UX workflow, just as Calibre-Web does within the "Set Metadata" page and others...)

- As such, PR #23 appears "backwards" — indeed it would literally takes the user backwards, closing the modal — when really the `Enter` key should either...
  1. Do absolutely nothing at all (hypercautious option!)
  2. Go forwards as if the "Start" button was clicked (current behavior, that appears fine so long as the user is rapidly informed as to what is happening!)
