### ISSUE TITLE
Metadata Fetch: [PLAYLIST URL] failed: An error occurred (no such column: live_status) while trying to connect to the database.

### ISSUE THREAD

**Issue by holta** [iiab/calibre-web#228]
Thanks @EMG70 for having reported this:

> A new error has appeared whilst trying to do a demo to a new IIAB user.This playlist in particular, https://www.youtube.com/playlist?list=PLqxP5EuGxPncYWWc1cXlcuhfcoo3Wl3Ru

> Metadata Fetch: [https://www.youtube.com/playlist?list=PLqxP5EuGxPncYWWc1cXlcuhfcoo3Wl3Ru] failed: An error occurred (no such column: live_status) while trying to connect to the database.

sudo iiab-diagnostics:
https://dpaste.com/EEE2QXLJB

![image](https://github.com/user-attachments/assets/20e85541-70af-4d22-aacb-57429d186d52)

Error details from https://dpaste.com/EEE2QXLJB#line-1911 :

```
[2024-07-20 17:03:48,505] ERROR {cps.services.worker:202} no such column: error
Traceback (most recent call last):
  File "/usr/local/calibre-web-py3/cps/services/worker.py", line 199, in start
    self.run(*args)
  File "/usr/local/calibre-web-py3/cps/tasks/metadata_extract.py", line 172, in run
    elif error_message := conn.execute("SELECT error FROM media WHERE ? LIKE '%' || extractor_id || '%'", (self.media_url,)).fetchone()[0]:
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: error
```

Potentially related:

- #186
- #188
- #199
- PR #211
- #212
- #215 
- PR #223

**Comment by holta** [comment]
@EMG70 clarifies:

> The same video playlist https://www.youtube.com/playlist?list=PLqxP5EuGxPncYWWc1cXlcuhfcoo3Wl3Ru downloads OK when done directly via yt-dlp, it is not a live playlist or denotated as such on Youtube.

**Comment by holta** [comment]
@EMG70 can you please confirm this is now solved?

(@deldesir believes it should have been resolved 5+ weeks ago by...)

- PR #191

**Comment by EMG70** [comment]
I have just tried ,all is now working.Apologies for late follow up.
