### ISSUE TITLE
xklb.log filling up with "Failed to connect to bus: No medium found"

### ISSUE THREAD

**Issue by holta** [iiab/calibre-web#230]
Can something be done about the majority of `/var/log/xklb.log` being polluted with such lines?

Example from https://dpaste.com/7ZXZ6TESL#line-2488

Thanks to @EMG70 testing Linux Mint 22 on a Lenovo ThinkCentre M93:

```
2024-07-24 14:38:15 - [Debug] Failed to connect to bus: No medium found
2024-07-24 14:38:15 - [Debug] ('systemd-run', '--user', '-p', 'MemoryMax=4G', '-p', 'MemorySwapMax=1G', '--pty', '--pipe', '--same-dir', '--wait', '--collect', '--service-type=exec', '--quiet', '--', 'ffmpeg', '-nostdin', '-hide_banner', '-nostats', '-xerror', '-v', '16', '-err_detect', 'explode', '-ss', '0.00', '-i', '/library/downloads/calibre-web/Youtube/Techy Plaza/12  Basic Searching_15.12k_[8vRFw6ZOqo8].mp4', '-t', '1', '-f', 'null', '/dev/null')
```

Alternate view of the same 2 lines:

> 2024-07-24 14:38:15 - [Debug] Failed to connect to bus: No medium found
2024-07-24 14:38:15 - [Debug] ('systemd-run', '--user', '-p', 'MemoryMax=4G', '-p', 'MemorySwapMax=1G', '--pty', '--pipe', '--same-dir', '--wait', '--collect', '--service-type=exec', '--quiet', '--', 'ffmpeg', '-nostdin', '-hide_banner', '-nostats', '-xerror', '-v', '16', '-err_detect', 'explode', '-ss', '0.00', '-i', '/library/downloads/calibre-web/Youtube/Techy Plaza/12  Basic Searching_15.12k_[8vRFw6ZOqo8].mp4', '-t', '1', '-f', 'null', '/dev/null')

**Comment by holta** [comment]
Background on `/var/log/xklb.log` :

- "How do I check logs?"
  https://github.com/iiab/calibre-web/wiki#how-do-i-check-logs

**Comment by chapmanjacobd** [comment]
I would say either don't run it under root user or don't log with debugging verbosity. 

Or if you don't want to do either maybe you can set `XDG_RUNTIME_DIR`

https://serverfault.com/questions/936985/cannot-use-systemctl-user-due-to-failed-to-get-d-bus-connection-permission

**Comment by holta** [comment]
> something is amiss with the way systemd is set up on your distribution !

FYI these are vanilla Linux Mint 22 and Ubuntu 24.04+ VMs, that have successfully downloaded 8vRFw6ZOqo8 using IIAB Calibre-Web.  I can try other OS's like Debian 12, Debian 13 if that proves necessary (?) but so far the issue would appear happen on all OS's.

> to be sure, it would be helpful to know the exit code for

Do the commands below shed any light?  (Any other commands I should try?!)

```
root@box:~# systemd-run --user -p MemoryMax=4G -p MemorySwapMax=1G --pty --pipe --same-dir --wait --collect --service-type=exec --quiet -- ffmpeg -nostdin -hide_banner -nostats -xerror -v 16 -err_detect explode -ss 0.00 -i '/library/downloads/calibre-web/Youtube/Techy Plaza/12 Basic Searching_15.12k_[8vRFw6ZOqo8].mp4' -t 1 -f null /dev/null
Failed to connect to bus: No medium found

root@box:~# tree /library/downloads/calibre-web/
/library/downloads/calibre-web/
└── Youtube
    └── Techy Plaza
```

```
root@box:~# locate .mp4
/library/calibre-web/Techy Plaza/12  Basic Searching (1)/12  Basic Searching - Techy Plaza.mp4

root@box:~# systemd-run --user -p MemoryMax=4G -p MemorySwapMax=1G --pty --pipe --same-dir --wait --collect --service-type=exec --quiet -- ffmpeg -nostdin -hide_banner -nostats -xerror -v 16 -err_detect explode -ss 0.00 -i '/library/calibre-web/Techy Plaza/12  Basic Searching (1)/12  Basic Searching - Techy Plaza.mp4' -t 1 -f null /dev/null
Failed to connect to bus: No medium found

root@box:~# tree /library/calibre-web/
/library/calibre-web/
├── Techy Plaza
│   └── 12  Basic Searching (1)
│       ├── 12  Basic Searching - Techy Plaza.mp4
│       └── cover.jpg
├── config
│   └── app.db
├── metadata.db
├── metadata_db_prefs_backup.json
└── xklb-metadata.db
```

> maybe you can set XDG_RUNTIME_DIR
>
> https://serverfault.com/questions/936985/cannot-use-systemctl-user-due-to-failed-to-get-d-bus-connection-permission

I'm not yet understanding, but am definitely willing to experiment if any such is the way to go?

```
root@box:~# env | grep XDG
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop

root@box:~# grep -r XDG /etc/xdg
/etc/xdg/user-dirs.conf:# the XDG_CONFIG_HOME and/or XDG_CONFIG_DIRS to override this

root@box:~# grep -r XDG_RUNTIME_DIR /etc
/etc/apparmor.d/usr.lib.snapd.snap-confine.real:    # for creating the user XDG_RUNTIME_DIR: /run/user, /run/user/UID and
/etc/X11/Xsession.d/20dbus_xdg-runtime:if [ -z "$DBUS_SESSION_BUS_ADDRESS" ] && [ -n "$XDG_RUNTIME_DIR" ] && \
/etc/X11/Xsession.d/20dbus_xdg-runtime:    [ "$XDG_RUNTIME_DIR" = "/run/user/`id -u`" ] && \
/etc/X11/Xsession.d/20dbus_xdg-runtime:    [ -S "$XDG_RUNTIME_DIR/bus" ]; then
/etc/X11/Xsession.d/20dbus_xdg-runtime:  # XDG_RUNTIME_DIR = "/run/user/`id -u`" is because we know that
/etc/X11/Xsession.d/20dbus_xdg-runtime:  DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus"
```

`/var/log/xklb.log` posted, as part of iiab-diagnostics: https://dpaste.com/AFHLNSES6#line-1194

**Comment by chapmanjacobd** [comment]
After running the command mentioned earlier, what is

    echo $?

I'm assuming it's 0

**Comment by holta** [comment]
```
root@box:~# systemd-run --user -p MemoryMax=4G -p MemorySwapMax=1G --pty --pipe --same-dir --wait --collect --service-type=exec --quiet -- ffmpeg -nostdin -hide_banner -nostats -xerror -v 16 -err_detect explode -ss 0.00 -i '/library/calibre-web/Techy Plaza/12  Basic Searching (1)/12  Basic Searching - Techy Plaza.mp4' -t 1 -f null /dev/null
Failed to connect to bus: No medium found

root@box:~# echo $?
1

root@box:~# systemd-run --user -p MemoryMax=4G -p MemorySwapMax=1G --pty --pipe --same-dir --wait --collect --service-type=exec --quiet -- ffmpeg -nostdin -hide_banner -nostats -xerror -v 16 -err_detect explode -ss 0.00 -i  NON-EXISTENT-FILE -t 1 -f null /dev/null
Failed to connect to bus: No medium found

root@box:~# echo $?
1
```

```
root@box:~# systemd-run -p MemoryMax=4G -p MemorySwapMax=1G --pty --pipe --same-dir --wait --collect --service-type=exec --quiet -- ffmpeg -nostdin -hide_banner -nostats -xerror -v 16 -err_detect explode -ss 0.00 -i '/library/calibre-web/Techy Plaza/12  Basic Searching (1)/12  Basic Searching - Techy Plaza.mp4' -t 1 -f null /dev/null

root@box:~# echo $?
0

root@box:~# systemd-run -p MemoryMax=4G -p MemorySwapMax=1G --pty --pipe --same-dir --wait --collect --service-type=exec --quiet -- ffmpeg -nostdin -hide_banner -nostats -xerror -v 16 -err_detect explode -ss 0.00 -i NON-EXISTENT-FILE -t 1 -f null /dev/null
[in#0 @ 0x61bc648b8a80] Error opening input: No such file or directory
Error opening input file NON-EXISTENT-FILE.
Error opening input files: No such file or directory

root@box:~# echo $?
254
```

**Comment by chapmanjacobd** [comment]
> root@box:~# systemd-run --user ...
> Failed to connect to bus: No medium found
> 
> root@box:~# echo $?
> 1

oh this seems like the opposite of what blondel told me. He said removing --user had no effect. maybe he was changing the wrong site-packages folder (ie. not pipx)

okay. In Ubuntu does checking for the "SUDO_UID" env var reliably indicate that the root user is the one launching the process?

**Comment by chapmanjacobd** [comment]
> still quite long-winded

It's debug level logging!! lol 😆 I'm not going to change that.

By default xklb does not write any logs to the filesystem. This is something that you are doing in your configuration

**Comment by holta** [comment]
> In Ubuntu does checking for the "SUDO_UID" env var reliably indicate that the root user is the one launching the process?

Seems extremely likely across {Debian, Raspberry Pi OS, Linux Mint, Ubuntu} which we care about most.

FWIW in bash I usually use:

```shell
if [[ $(id -un) != "root" ]]; then
    echo "You're not root"
fi
```

> verbosity of the logs

PS More verbose debug-level logging is great!

- I just had no idea whether-or-not those 11 long lines (nearly identical, and seemingly very rapid-fire) were unnecessarily stepping on each other i.e. overly repetitious ⚠️

- But if they're genuinely helping, that's indeed all the matters ✅

**Comment by chapmanjacobd** [comment]
okay the latest version should fix the bug with running as root and the logging should always print out nonzero exit codes (except in the few places that are managed with Popen directly rather than using the xklb cmd util)

https://github.com/chapmanjacobd/library/compare/v2.9.005...v2.9.006
