### ISSUE TITLE
Delete video/book

### ISSUE THREAD

**Issue by avni** [iiab/calibre-web#237]
**Is your feature request related to a problem? Please describe.**
I would like to be able to delete books/videos from an instance (I accidentally downloaded the same video 2 times into an instance and would like to delete one of them).

**Describe the solution you'd like**
1. Go to: http://box/books/ to see you list of books
2. Click on a book. An overlay pops up with details. 
3. It would be nice to have a delete function (in addition to the archive function) available from this overlay. 

UX: It could potentially be a red button, entitled, "Delete" in the lower left of the overlay. 

**Describe alternatives you've considered**
Archiving removes content from the main calibre-web page, but if you make a mistake like I did and upload the same video 2x, it would be good to be able to delete it completely. Alternatively/additionally, if calibre-web can detect that a video is a duplicate and not upload the second instance, that would be amazing!

**Additional context**
Screenshot showing 2 duplicate videos along with a 3rd unique video: 

![Image](https://github.com/user-attachments/assets/3a71281f-8c1f-4734-9c35-0ac807742a66)

**Comment by holta** [comment]
@avni do you know about the "Delete Book" **red button** (top-left, under the thumbnail) within every book's / every video's "Edit Metadata" ?

**Comment by holta** [comment]
My opinion is that we should try hard not to deviate from the upstream/official version Calibre-Web UI/UX at this time, unless absolutely necessary!?

(And if very serious UI/UX problems arise in Calibre-Web, which will happen from time to time, can we please try to steer those questions + concerns upstream to https://github.com/janeczku/calibre-web as much as possible, this year especially?)

PS Thanks to @deldesir for mentioning this!

**Comment by avni** [comment]
> @avni do you know about the "Delete Book" red button (top-left, under the thumbnail) within every book's / every video's "Edit Metadata" ?

No I was not aware of that!  It may be a bit more user friendly to have a button on the Details overlay but not required. 

> (And if very serious UI/UX problems arise in Calibre-Web, which will happen from time to time, can we please try to steer those questions + concerns upstream to https://github.com/janeczku/calibre-web as much as possible, this year especially?)

Ah good point. 

Closing.
