### ISSUE TITLE
Pressing 'Enter' fails to advance the 'Download' modal, regardless whether it contains a valid URL or not

### ISSUE THREAD

**Issue by holta** [iiab/calibre-web#24]
Custom UX work is definitely not the goal!

But yesterday's long discussion in these 2 places does not correspond to reality:

- #22
- PR #23

The reality is that pressing `Enter` does not currently advance the `Download` modal, as if the `Start` button was pressed.

(So articulated intention needs to be aligned with code — in the simplest possible way, in one way or another — avoiding custom UX code as much as humanly possible anyway!)

**Comment by deldesir** [comment]
Did you clear your browser cache?

**Comment by holta** [comment]
This bug report was erroneous.

As VM was built from https://github.com/deldesir/calibre-web

I've since confirmed that #22 and PR #23 work as expected when VM is built properly with https://github.com/iiab/calibre-web
