### ISSUE TITLE
Media download request fails on standard endpoints [RE: hardcoded /live/media in main.js AND /books /libros /livres ETC]

### ISSUE THREAD

**Issue by deldesir** [iiab/calibre-web#25]
Standard endpoints per https://github.com/iiab/iiab/blob/master/vars/default_vars.yml#L661-L663 will fail unless it is /live/media.

**Comment by holta** [comment]
Bug is:

https://github.com/iiab/calibre-web/blob/6bee01578b9dec09b6447495ed4d4e6b430cac29/cps/static/js/main.js#L192

1. Default should be http://box/books not http://box/live
2. Actionable documentation needs to make clear within https://github.com/iiab/calibre-web/wiki explaning exactly what files to change if your [/etc/iiab/local_vars.yml](https://wiki.iiab.io/go/FAQ#What_is_local_vars.yml_and_how_do_I_customize_it?) has customized variables like these three:
   ```
   calibreweb_url1: /books     # For SHORT URL http://box/books  (English)
   calibreweb_url2: /libros    # For SHORT URL http://box/libros (Spanish)
   calibreweb_url3: /livres    # For SHORT URL http://box/livres (French)
   ```
   https://github.com/iiab/iiab/blob/579cfac36eca6e8c3916b4d91fa4c430bbf69cbf/vars/default_vars.yml#L661-L663
