### ISSUE TITLE
Run time is buggy in https://github.com/iiab/calibre-web/pull/257

### ISSUE THREAD

**Issue by deldesir** [iiab/calibre-web#273]
Reminder for @deldesir: Periodic refreshing is happening every 1000ms in Tasks page ( I wish I knew this when dealing with race conditions months ago). Fix this by using end_time in a loop.

**Comment by holta** [comment]
Related:

- PR #257

**Comment by deldesir** [comment]
Fixed in 68db009088d536cc6ffe1a9e51b7355eb59c31fb
