### ISSUE TITLE
Video downloads all appear as "Failed" after clicking on 'Tasks' button

### ISSUE THREAD

**Issue by holta** [iiab/calibre-web#29]
A few examples below, thanks to @EMG70:

![image](https://github.com/iiab/calibre-web/assets/2458907/a8f10720-3440-4f37-97b3-23b49bcb540d)

**Comment by holta** [comment]
@deldesir mentions this issue is related to...

- #25
- PR #26

**Comment by holta** [comment]
@deldesir is there a chance this (#29) might have been solved by... ?

- PR #26

**Comment by EMG70** [comment]
Latest test results:

>
![IMG_1710](https://github.com/iiab/calibre-web/assets/52469992/326cf991-4211-4954-b32f-35a23d61f633)
![IMG_1709](https://github.com/iiab/calibre-web/assets/52469992/534276b1-e69f-4590-9031-9ee2adf69f60)
![IMG_1711](https://github.com/iiab/calibre-web/assets/52469992/5f905ccf-5551-48f5-b25f-b8bc66bbf592)
![5D936B77-C6A4-49C5-AFD2-16CBFDAB1FAB](https://github.com/iiab/calibre-web/assets/52469992/160b011f-c933-4255-adf3-19c735818c1a)
![867F9C80-EFD2-4FB3-A91A-BF7058AE165E](https://github.com/iiab/calibre-web/assets/52469992/5b172be9-3a1e-43ca-8935-fdb669f0b974)
![7520C5DA-3481-46A2-A438-42064C64CCC8](https://github.com/iiab/calibre-web/assets/52469992/0bb92adb-aabc-4dc1-bcab-f1eec3cc3ee2)

**Comment by EMG70** [comment]
Additionally, There’s a menu to update database and update calibre,tried that and now can’t logon,bad gateway
![2B1E1FF8-2889-4BBA-9F19-DC339D12353F](https://github.com/iiab/calibre-web/assets/52469992/b1017d11-32e8-4d6d-8972-8d7c0d487f3a)

**Comment by deldesir** [comment]
I 

> Latest test results:
> 
> > 
> 
> ![867F9C80-EFD2-4FB3-A91A-BF7058AE165E](https://user-images.githubusercontent.com/52469992/282138518-5b172be9-3a1e-43ca-8935-fdb669f0b974.jpeg) ![7520C5DA-3481-46A2-A438-42064C64CCC8](https://user-images.githubusercontent.com/52469992/282138536-0bb92adb-aabc-4dc1-bcab-f1eec3cc3ee2.jpeg)

I can see yb (the xklb wrapper) is not available in /usr/local/bin. It's currently maintained at https://github.com/deldesir/lb-wrapper.

**Comment by holta** [comment]
Huge thanks @EMG70 for catching this.  Apologies the install instructions aren't quite yet 100% complete:

https://github.com/iiab/calibre-web/wiki#install

( Hopefully that'll be solved Monday — or ideally beforehand 🙏 )

**Comment by EMG70** [comment]
![FF3EADE7-C6CD-4756-9BBD-035ADFD58427](https://github.com/iiab/calibre-web/assets/52469992/6f8ec3a8-7a2d-4b80-9128-064e58121581)

**Comment by EMG70** [comment]
All working Good 👍
