### ISSUE TITLE
Full description missing for downloaded videos

### ISSUE THREAD

**Issue by deldesir** [iiab/calibre-web#67]
![Screenshot 2023-12-18 114636](https://github.com/iiab/calibre-web/assets/2458907/6ef369f8-6b16-4185-818d-9fa013b62616)

Full description(s) text/paragraphs now appear missing — see the screenshot above — apparently due to an upstream change or regression in xklb ?

```
root@box:~# yt-dlp --version
2023.11.16
root@box:~# lb --version
2.2.186
root@box:~# hostname -I
10.181.233.245 192.168.0.117 10.8.0.46 fd42:fb6b:9c93:d2f1:5054:ff:fe1b:116f
root@box:~# hostname -A
t4.lxd box box t4.lxd
root@box:~# cat /etc/issue
Ubuntu Noble Numbat (development branch) \n \l
```

_Originally posted by @holta in https://github.com/iiab/calibre-web/issues/65#issuecomment-1861051732_

**Comment by holta** [comment]
Tangentially related:

- #11
- #52
