### ISSUE TITLE
Support additional media upload and download 

### ISSUE THREAD

**Issue by deldesir** [iiab/calibre-web#7]
**Problem Statement:** 
Calibre-Web is a robust platform designed for managing e-books efficiently. However, users often find the need to organize their personal multimedia content (videos, photos, audios) alongside their digital book collection. Presently, there's no seamless provision to integrate and manage these diverse media types within Calibre-Web.

**Proposed Solution:**
This expansion to support multimedia content is crucial. By incorporating support for various media formats (videos, photos, audios), users can effortlessly upload, organize, and manage their diverse digital media collections. Ensuring metadata persistence in the database will allow for easy categorization and searching. Additionally, implementing a feature to download videos from popular platforms directly into Calibre-Web would significantly enhance its utility.

**Detailed Feature Specifications:**
1. **Multimedia Upload Support:** Enable the uploading of various media formats supported by major browsers (e.g., MP4, WEBM for videos; JPEG, PNG for images; MP3, OGG and WAV for audios).
2. **Metadata Handling:** Implement a system to persist metadata associated with each uploaded media file (e.g., title, description, author, date, etc.).
3. **Integration with Online Platforms:** Provide an option to download videos directly from popular platforms (such as YouTube, Vimeo) for seamless integration and management.
![Screenshot from 2023-11-01 10-35-11](https://github.com/iiab/calibre-web/assets/16546989/231f109e-cadc-4aac-8547-bdb3342e1d1f)

**Alternatives Considered:**
- **Custom Plugin Development:** While a custom plugin could address this need, maintaining it separately might introduce complexities. Integrating these features directly within Calibre-Web would provide a more seamless and integrated solution for users.

**Comment by holta** [comment]
Apologies that I auto-closed this issue unintentionally!

(Seems to have happened automatically when I merged...)

- PR #6

**Comment by holta** [comment]
1) @EMG70 can you review the explanation above with me, if you have time in the coming week?

2) Also please let us know **what's missing** from this EARLY DRAFT documentation:
https://github.com/iiab/calibre-web/wiki

Huge Thanks! 🙏

**Comment by EMG70** [comment]
This looks good and easy to use by Teachers or librarians. 👍

**Comment by holta** [comment]
Implemented / Fixed by...

- PR #19
