### ISSUE TITLE
Add xklb version [and more, to friendlier & more efficient logging]

### ISSUE THREAD

**Issue by deldesir** [iiab/calibre-web#70]
How about including the xklb version information in the logfile upon each execution of the tool? This addition will facilitate the identification of the exact version that is associated with any observed regressions or bugs.

_Based on question posted by @holta in https://github.com/chapmanjacobd/library/issues/23#issuecomment-1863286733_

**Comment by holta** [comment]
Somewhat related:

- #68

**Comment by holta** [comment]
- yt-dlp version too, should be recorded!

- Any other files & "illustrative reporting" commands @deldesir recommends?

- Output from these 2 commands might be very wise over coming weeks:

   ```
   tree /library/downloads/calibre-web/
   tree /library/calibre-web/
   ```

- Bug-reporting template urgently needs overhaul: https://github.com/iiab/calibre-web/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

- Create another "instant script" like iiab-diagnostics (https://github.com/iiab/iiab/blob/master/scripts/iiab-diagnostics.README.md) if necessary ?

- Unified logging via systemctl / journalctl should be considered! #68

**Comment by holta** [comment]
Please see progress ongoing trying to surface meaningful diagnostics and error messages:

- PR #93
- PR #94
- PR #95
- PR iiab/iiab#3697
- PR iiab/iiab#3698

**Comment by holta** [comment]
If we consider Clean + Meaningful logging to be the foundation upon which everything is built — here's a smaller issue that should be answered and/or resolved in coming weeks:

- #100

**Comment by deldesir** [comment]
Done. Please close.

**Comment by holta** [comment]
Logging like user-facing error messages still need work, but yes logging is dramatically better now 6 months later!

Thanks to PRs along the way, including:

- PR iiab/iiab#3752
