### ISSUE TITLE
/var/log/calibre-web.log shows "WARN {py.warnings:109} /usr/local/calibre-web-py3/lib/python3.11/site-packages/flask_limiter/extension.py:336: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.   warnings.warn("

### ISSUE THREAD

**Issue by holta** [iiab/calibre-web#73]
@deldesir any idea how serious this warning is?  /var/log/calibre-web.log shows the following warning — followed by a mysterious blank line:

> WARN {py.warnings:109} /usr/local/calibre-web-py3/lib/python3.11/site-packages/flask_limiter/extension.py:336: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.   warnings.warn(

Example/details to reproduce this:

- https://github.com/iiab/calibre-web/issues/61#issuecomment-1866709354

**Comment by deldesir** [comment]
The buffersize limit of Tornado, it seems.

**Comment by holta** [comment]
@deldesir should this ticket be closed?

(Is it fully resolved by... ?)

- PR #75

**Comment by deldesir** [comment]
Yes, it's no more relevant.
