### ISSUE TITLE
Upgrade Calibre-Web to latest IIAB version [works! But Vimeo download glitch]

### ISSUE THREAD

**Issue by EMG70** [iiab/calibre-web#76]
**Describe the bug/problem**
Upgraded iiab small size OK.MP4 videos downloaded ok from Youtube and Vimeo.
one of vimeo videos downloaded 100% in task but not showing in books page.
https://vimeo.com/238136107
Upload of red ears https://vp.nyt.com/video/2023/10/23/112532_1_opdoc-redears_wg_1080p.mp4 causes bad gateway crash and access to Calibre not achievable after. I managed to reboot server in admin console and all came back Ok but without history of downloaded tasks .All videos still showed Ok.

**To Reproduce**
Upgrade IIAB and test again.

**Logfile**
root@box:/# pastebinit -b [sprunge.us](http://sprunge.us/) /var/log/calibre-web.log
http://sprunge.us/y5kuXE?en
root@box:/#  pastebinit -b [sprunge.us](http://sprunge.us/) /var/log/xklb.log
http://sprunge.us/yvtnHw?en
 IIAB diagnostics after upgrade-http://sprunge.us/5uNQ3M?en
IIAB diagnostics after video downloads -http://sprunge.us/3SKXUE?en
IIAB diagnostics after video upload  red ears https://vp.nyt.com/video/2023/10/23/112532_1_opdoc-redears_wg_1080p.mp4 - http://sprunge.us/D8wjT3?en

**Expected behavior**
Upgrade works as expected minus known outstanding issues with Calibre-Web

**Screenshots**
![Screenshot from 2023-12-22 18-05-35](https://github.com/iiab/calibre-web/assets/52469992/23650a8c-0aa4-4fed-945b-3467bf3bb134)
![Screenshot from 2023-12-22 17-23-23](https://github.com/iiab/calibre-web/assets/52469992/1fd0a512-01cc-4d35-bf0b-f71e35e9cb22)

**Environment (please complete the following information):**
 
![Screenshot from 2023-12-22 18-17-23](https://github.com/iiab/calibre-web/assets/52469992/afc8381d-a640-4d47-833f-6692c48a7005)

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by holta** [comment]
Thanks @EMG70 for having confirmed — that almost any Internet-in-a-Box with an older version of Calibre-Web can now upgrade: 🔥

https://github.com/iiab/calibre-web/wiki#upgrading

@deldesir is the Vimeo glitch understandable to you?

**Comment by deldesir** [comment]
Looks like it's a /media endpoint issue. This means this happen on a specific page. Do you remember the actual page you were in right before you clicked on the Download to IIAB button @EMG70?

Context: ```http://192.168.0.11/books/media?data=format&sort_param=stored```

**Comment by deldesir** [comment]
I confirm it's not a media endpoint issue. I tested this locally. I am investigating further.

**Comment by EMG70** [comment]
> Looks like it's a /media endpoint issue. This means this happen on a specific page.
> 
> @EMG70, do you remember the actual page you were in right before you clicked on the `Download to IIAB` button?
> 
> Context: `http://192.168.0.11/books/media?data=format&sort_param=stored`

Indeed,this looks like a particular vimeo video (https://vimeo.com/238136107 ) that failed.This video https://vimeo.com/70397084 did download and showed Ok from vimeo.

**Comment by EMG70** [comment]
Update:
The same previously failed video  https://vimeo.com/238136107 has just downloaded and showed on home page when video quality option is set to 1080p
root@box:~# pastebinit -b sprunge.us /var/log/calibre-web.log
http://sprunge.us/4QnuWQ?
root@box:~# pastebinit -b sprunge.us /var/log/xklb.log
http://sprunge.us/jLyyIx?en

**Comment by EMG70** [comment]
Tested same video under 3 modes 480p 720p 1080p and all OK now.I am not sure what happened earlier.
![Screenshot from 2023-12-22 20-02-39](https://github.com/iiab/calibre-web/assets/52469992/1e3a7eb9-24b7-40fe-821d-0f55f8132505)
![Screenshot from 2023-12-22 20-04-12](https://github.com/iiab/calibre-web/assets/52469992/e6a791c7-67c3-4b6b-868e-1c7b6d7f0bb3)
pastebinit -b sprunge.us /var/log/calibre-web.log
http://sprunge.us/xVVwAT
pastebinit -b sprunge.us /var/log/xklb.log
http://sprunge.us/tOX6BV

**Comment by deldesir** [comment]
Thank you @EMG70 for providing this update on your testing. Glad to hear that the video download is now working as expected in all three modes (480p, 720p, 1080p). I appreciate you investigated this further with diligence.

**Comment by holta** [comment]
Should this ticket now be closed and labeled "Cannot Reproduce" ?

(Ideally with a quick explanation as to why Vimeo download(s) might have been failing earlier?)

Just to Confirm: Is https://vimeo.com/238136107 now downloading "correctly" for everyone?

**Comment by holta** [comment]
@EMG70 ping'd me to confirm it's a mystery (not reproducible!)

Please re-open this ticket at a later date if necessary, Thanks 🙏

**Comment by EMG70** [comment]
Ten vimeo short videos downloaded successively and all showed on on homepage.
A second attempt was made to download al 10 urls at once and successfully downloaded after 4mins.
screenshots for the 10 batch download:
https://vimeo.com/101260809
https://vimeo.com/125696078
https://vimeo.com/218538912
https://vimeo.com/22030635
https://vimeo.com/222470400
https://vimeo.com/241673906
https://vimeo.com/245466297
https://vimeo.com/381271095
https://vimeo.com/452371533
https://vimeo.com/9582297

![Screenshot from 2023-12-27 15-07-05](https://github.com/iiab/calibre-web/assets/52469992/f66e94b9-4fc0-47f8-a741-ab361dd67367)
![Screenshot from 2023-12-27 15-11-08](https://github.com/iiab/calibre-web/assets/52469992/703d7613-ac15-46ae-97f2-d7164ac191d1)
![Screenshot from 2023-12-27 15-15-24](https://github.com/iiab/calibre-web/assets/52469992/16c4eba7-7446-436e-8363-181f909b83a4)

iiab-diagnostics http://sprunge.us/TP4J9q?en

pastebinit -b sprunge.us /var/log/calibre-web.log
http://sprunge.us/taqvIe?en
pastebinit -b sprunge.us /var/log/xklb.log
http://sprunge.us/uD5CWo?en
