### ISSUE TITLE
Enhance download task messages for improved information when downloading a video

### ISSUE THREAD

**Issue by deldesir** [iiab/calibre-web#89]
**Is your feature request related to a problem? Please describe.**
The current download task messages lack sufficient detail, leading to a less informative monitoring.

**Describe the solution you'd like**
I would like to enhance the download task messages by updating them dynamically. This improvement aims to provide context-specific status information during the download process.

**Describe alternatives you've considered**
Alternative solutions include sticking with the existing messaging approach or implementing a less comprehensive update. However, these alternatives may not address the need for improved user understanding and monitoring capabilities as effectively.

**Additional context**
The proposed changes align with the work already done in PR #88 . This feature request is driven by the intention to provide insights during the download process. We will track it in PR 90.

**Comment by holta** [comment]
@deldesir less urgent but question for the future:

Will "Tasks" view also show explanatory error messages when YouTube playlists or channels fail to download?

**Comment by deldesir** [comment]
Yes, that's possible. The messages will be updated then with the error text.

**Comment by deldesir** [comment]
Duplicate of #85. Please close.

**Comment by holta** [comment]
> Duplicate of #85. Please close.

These being "umbrella" tickets, progress is and will be ongoing thanks to PRs like:

- PR #90

Tangentially related:

- https://github.com/iiab/calibre-web/issues/70#issuecomment-2182899715
