### ISSUE TITLE
Playlist downloads will report a 500 INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by deldesir** [iiab/calibre-web#98]
Bookshelf feature will work but report a 500 INTERNAL SERVER ERROR in Tasks view.

_Originally posted by @deldesir in https://github.com/iiab/calibre-web/issues/97#issuecomment-1892725195_

**Comment by holta** [comment]
Thanks much @deldesir for investigating! 💯

This problem is likely a side effect of my "move instead of copy [video files]" PR from 2 weeks ago here...

- PR #82

**Comment by holta** [comment]
Just FYI work is ongoing here to solve #98 — as the following PR is being rethought and/or reworked: 

- PR #99

**Comment by holta** [comment]
Solved by...

- PR #102

...thanks to @deldesir ✅
